### ISSUE TITLE
Redundant constructor

### ISSUE THREAD

**Issue by asbjornenge** [stove-labs/tzip-12-tutorial#4]
Hi there!

I was following your [tutorial](https://medium.com/@matej.sima/tutorial-implementing-a-mini-token-contract-on-tezos-with-on-chain-callbacks-tzip-12-b04cf7ee2059) but got stuck on a `redundant constructor` error.

Tried checking out this repo, but getting same error:

```
Compiling your contracts...
===========================
> Compiling ./contracts/main/Migrations.ligo
> Compiling ./contracts/main/balance_requester.ligo
> Compiling ./contracts/main/tzip_12_tutorial.ligo
> Using entry point "main"
ligo: redundant constructor:  {"constructor":"Receive_balance", 
..........

Compilation of /srv/asbjornenge/tzip-12-tutorial/contracts/main/balance_requester.ligo failed. See above.
Truffle v5.2.0-tezos.1 (core: 5.2.0-tezos.1)
Node v13.12.0
```

Could it be the version of `ligo` not supporting something in your syntax?

**Comment by maht0rz** [comment]
Hi @asbjornenge, thanks for reporting the issue i'm checking it now :)

**Comment by maht0rz** [comment]
Fixed in https://github.com/stove-labs/tzip-12-tutorial/commit/cfe50b744b31817a8250152060b2b2b30e14cdc0
